version: "2.0"

nlu:
- intent: action::caesar_salad
  examples: |
    - caesar salad
    - I want to make caesar salad
    - I want the recipe of the caesar salad
    - could you explain to me how to make a caesar salad?

- intent: action::french_omelette
  examples: |
    - french omelette
    - I want to make french omelette
    - I want the recipe of a french omelette
    - how can I make a french omelette?

- intent: question::ingredient_amount
  examples: |
    - how much [butter]{"entity": "sort.ingredient", "value": "individual.butter"} should I use?
    - how much [caesar sauce]{"entity": "sort.ingredient", "value": "individual.caesar_sauce"} should I use?
    - how much [lettuce]{"entity": "sort.ingredient", "value": "individual.lettuce"} should I use?
    - how much [of course! some people like to add half-cut cherry tomatoes or a can of sweet corn]{"entity": "sort.ingredient", "value": "individual.extra_caesar"} should I use?
    - how much [of course! you can add some muchroom and cheese inside the omelette before you fold it]{"entity": "sort.ingredient", "value": "individual.extra_omelette"} should I use?
    - how much [parmesan]{"entity": "sort.ingredient", "value": "individual.parmesan"} should I use?
    - how much [butter]{"entity": "sort.ingredient", "value": "individual.butter"} does it need?
    - how much [caesar sauce]{"entity": "sort.ingredient", "value": "individual.caesar_sauce"} does it need?
    - how much [lettuce]{"entity": "sort.ingredient", "value": "individual.lettuce"} does it need?
    - how much [of course! some people like to add half-cut cherry tomatoes or a can of sweet corn]{"entity": "sort.ingredient", "value": "individual.extra_caesar"} does it need?
    - how much [of course! you can add some muchroom and cheese inside the omelette before you fold it]{"entity": "sort.ingredient", "value": "individual.extra_omelette"} does it need?
    - how much [parmesan]{"entity": "sort.ingredient", "value": "individual.parmesan"} does it need?
    - what is the amount of the [butter]{"entity": "sort.ingredient", "value": "individual.butter"}?
    - what is the amount of the [caesar sauce]{"entity": "sort.ingredient", "value": "individual.caesar_sauce"}?
    - what is the amount of the [lettuce]{"entity": "sort.ingredient", "value": "individual.lettuce"}?
    - what is the amount of the [of course! some people like to add half-cut cherry tomatoes or a can of sweet corn]{"entity": "sort.ingredient", "value": "individual.extra_caesar"}?
    - what is the amount of the [of course! you can add some muchroom and cheese inside the omelette before you fold it]{"entity": "sort.ingredient", "value": "individual.extra_omelette"}?
    - what is the amount of the [parmesan]{"entity": "sort.ingredient", "value": "individual.parmesan"}?
    - how much [butter]{"entity": "sort.ingredient", "value": "individual.butter"} should I use?
    - how much [caesar sauce]{"entity": "sort.ingredient", "value": "individual.caesar_sauce"} should I use?
    - how much [lettuce]{"entity": "sort.ingredient", "value": "individual.lettuce"} should I use?
    - how much [of course! some people like to add half-cut cherry tomatoes or a can of sweet corn]{"entity": "sort.ingredient", "value": "individual.extra_caesar"} should I use?
    - how much [of course! you can add some muchroom and cheese inside the omelette before you fold it]{"entity": "sort.ingredient", "value": "individual.extra_omelette"} should I use?
    - how much [parmesan]{"entity": "sort.ingredient", "value": "individual.parmesan"} should I use?

- intent: question::extra_ingredient
  examples: |
    - Do you suggest adding any other ingredients?
    - Could you help me suggesting to add other ingredients to the recipe?
    - What would be other suitable ingredients to the recipe?
    - I would love to add extra ingredients to the recipe, do you have any suggestions?

- intent: answer
  examples: |
    - [butter]{"entity": "sort.ingredient", "value": "individual.butter"}
    - [lettuce]{"entity": "sort.ingredient", "value": "individual.lettuce"}
    - [parmesan]{"entity": "sort.ingredient", "value": "individual.parmesan"}
    - [caesar sauce]{"entity": "sort.ingredient", "value": "individual.caesar_sauce"}
    - [of course! you can add some muchroom and cheese inside the omelette before you fold it]{"entity": "sort.ingredient", "value": "individual.extra_omelette"}
    - [of course! some people like to add half-cut cherry tomatoes or a can of sweet corn]{"entity": "sort.ingredient", "value": "individual.extra_caesar"}
    - [Amazing! You have finished preparing a French omelette. Bon appétit!]{"entity": "sort.is_served", "value": "individual.here_omelette"}
    - [Amazing! now you have the most delicious caesar salad ever. Bon appétit!]{"entity": "sort.is_served", "value": "individual.here_salad"}
    - [add one spoon of butter or oil]{"entity": "sort.amount", "value": "individual.butter_amount"}
    - [you will need half a lettuce]{"entity": "sort.amount", "value": "individual.lettuce_amount"}
    - [this is optional, but it's recommended to put almost one table spoon, either grated or ground]{"entity": "sort.amount", "value": "individual.parmesan_amount"}
    - [two table spoons is sufficeint]{"entity": "sort.amount", "value": "individual.sauce_amount"}
    - [omelette]{"entity": "sort.recipe", "value": "individual.omelette"}
    - [salad]{"entity": "sort.recipe", "value": "individual.salad"}
    - yes [butter]{"entity": "sort.ingredient", "value": "individual.butter"}
    - yes [this is optional, but it's recommended to put almost one table spoon, either grated or ground]{"entity": "sort.amount", "value": "individual.parmesan_amount"}
    - no [lettuce]{"entity": "sort.ingredient", "value": "individual.lettuce"}
    - no [two table spoons is sufficeint]{"entity": "sort.amount", "value": "individual.sauce_amount"}

- intent: answer_negation
  examples: |
    - not [butter]{"entity": "sort.ingredient", "value": "individual.butter"}
    - not [lettuce]{"entity": "sort.ingredient", "value": "individual.lettuce"}
    - not [parmesan]{"entity": "sort.ingredient", "value": "individual.parmesan"}
    - not [caesar sauce]{"entity": "sort.ingredient", "value": "individual.caesar_sauce"}
    - not [of course! you can add some muchroom and cheese inside the omelette before you fold it]{"entity": "sort.ingredient", "value": "individual.extra_omelette"}
    - not [of course! some people like to add half-cut cherry tomatoes or a can of sweet corn]{"entity": "sort.ingredient", "value": "individual.extra_caesar"}
    - not [Amazing! You have finished preparing a French omelette. Bon appétit!]{"entity": "sort.is_served", "value": "individual.here_omelette"}
    - not [Amazing! now you have the most delicious caesar salad ever. Bon appétit!]{"entity": "sort.is_served", "value": "individual.here_salad"}
    - not [add one spoon of butter or oil]{"entity": "sort.amount", "value": "individual.butter_amount"}
    - not [you will need half a lettuce]{"entity": "sort.amount", "value": "individual.lettuce_amount"}
    - not [this is optional, but it's recommended to put almost one table spoon, either grated or ground]{"entity": "sort.amount", "value": "individual.parmesan_amount"}
    - not [two table spoons is sufficeint]{"entity": "sort.amount", "value": "individual.sauce_amount"}
    - not [omelette]{"entity": "sort.recipe", "value": "individual.omelette"}
    - not [salad]{"entity": "sort.recipe", "value": "individual.salad"}

- intent: NEGATIVE
  examples: |
    - aboard
    - about
    - above
    - across
    - after
    - against
    - along
    - among
    - as
    - at
    - on
    - atop
    - before
    - behind
    - below
    - beneath
    - beside
    - between
    - beyond
    - but
    - by
    - come
    - down
    - during
    - except
    - for
    - from
    - in
    - inside
    - into
    - less
    - like
    - near
    - of
    - off
    - on
    - onto
    - opposite
    - out
    - outside
    - over
    - past
    - save
    - short
    - since
    - than
    - then
    - through
    - throughout
    - to
    - toward
    - under
    - underneath
    - unlike
    - until
    - up
    - upon
    - with
    - within
    - without
    - worth
    - is
    - it
    - the
    - a
    - am
    - are
    - them
    - this
    - that
    - I
    - you
    - he
    - she
    - they
    - them
    - his
    - her
    - my
    - mine
    - their
    - your
    - us
    - our
    - how
    - how's
    - how is
    - how's the
    - how is the
    - when
    - when's
    - when is
    - when is the
    - when's the
    - what
    - what is
    - what's
    - what's the
    - what is the
    - why
    - why is
    - why's
    - why is the
    - why's the
    - do
    - make
    - tell
    - start
    - stop
    - enable
    - disable
    - raise
    - lower
    - decrease
    - increase
    - act
    - determine
    - say
    - ask
    - go
    - shoot
    - wait
    - hang on
    - ok
    - show
    - help

- intent: answer:yes
  examples: |
    - yes
    - yeah
    - yep
    - sure
    - ok
    - of course
    - very well
    - fine
    - right
    - excellent
    - okay
    - perfect
    - I think so

- intent: answer:no
  examples: |
    - no
    - nope
    - no thanks
    - no thank you
    - negative
    - don't want to
    - don't
    - do not
    - please don't

- intent: request:top
  examples: |
    - forget it
    - never mind
    - get me out of here
    - start over
    - beginning
    - never mind that
    - restart

- intent: request:up
  examples: |
    - go back
    - back
    - previous
    - back to the previous
    - go to the previous
    - go back to the previous one

- intent: request:how
  examples: |
    - how do I do that
    - how
    - can you tell me how to do that
    - I don't know how should I do that
    - how can I do that

- intent: report:done
  examples: |
    - I'm done
    - done
    - ready
    - it's ready
    - I'm ready
    - completed
    - check
    - I have finished
    - finished
    - done and done
    - it's done now
    - okay next
    - next
    - next instruction

- intent: icm:per*neg
  examples: |
    - repeat
    - repeat it
    - repeat that
    - pardon
    - sorry
    - can you repeat that
    - excuse me
    - what was that
    - what did you say
    - come again

- intent: icm:acc*neg:issue
  examples: |
    - I don't know
    - I don't know that
    - it doesn't matter

- intent: thanks
  examples: |
    - thank you
    - thank you very much
    - thanks
    - big thanks
    - thanks a lot

- intent: greet
  examples: |
    - hello
    - hi
    - good day
    - what's up
    - good evening
    - good morning
    - hey


